language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - nkw8620@gmail.com

before_deploy:
  - zip -r spring-webservice-book *
  - mkdir -p deploy
  - mv spring-webservice-book.zip deploy/spring-webservice-book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-book-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-book-build
    key: spring-webservice-book.zip
    bundle_type: zip
    application: spring-webservice-book
    deployment_group: spring-webservice-book-group
    region: ap-northeast-2
    wait-until-deployed: true